name: image_carousel
author: Theo Bouwman <theobouwman98@gmail.com>
homepage: https://github.com/theobouwman/flutter_image_carousel
description: A image carousel flutter plugin
version: 0.4.2

environment:
  sdk: '>=2.00.0'

dependencies:
  zoomable_image: ^1.3.1

  flutter:
    sdk: flutter
